version: "3"

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Mappage du port 80 du conteneur vers le port 8000 de l'hôte
    volumes:
      - ./:/django_project
    command: ["python3", "./app/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
      - apache

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/django_project
    command: ["apache2ctl", "-D", "FOREGROUND"]

volumes:
  pgdata:
