version: "3"

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/election_python_version
    command: /bin/bash -c "python manage.py migrate && python3 manage.py runserver '0.0.0.0:8000'"
